---
- name: Create production directory
  file:
    path: "{{ production_directory }}"
    state: directory
    mode: '0755'

- name: list artifacts
  find:
    hidden: yes
    paths: "{{ artifact_directory }}"
    recurse: no
    file_type: directory
  register: artifacts

- name: copy file from artifact dir to production dir
  copy:
    remote_src: yes
    src: "{{ artifact_directory }}/{{ item.path | basename }}"
    dest: "{{ production_directory }}/"
  with_items: "{{ artifacts.files }}"

- name: create symbolic link to XDG_CONFIG_HOME
  file:
    state: link
    src: "{{ production_directory }}/{{ item }}"
    dest: "{{ xdg_config }}/{{ item }}"
  with_items:
    - awesome
    - conky
    - fish
    - nvim
    - picom 
    - rofi
    - omf
    - neofetch

- name: list @home file
  find:
    paths: "{{ production_directory }}/@home"
    hidden: yes
    recurse: no
  register: files

- name: "@home"
  file:
    state: link
    src: "{{ item.path }}"
    dest: "{{ home }}/{{ item.path | basename }}"
  with_items: "{{ files.files }}"
